### ISSUE TITLE
No data incoming

### ISSUE THREAD

**Issue by danroth77** [tolwi/hassio-ecoflow-cloud#107]
### Discussed in https://github.com/tolwi/hassio-ecoflow-cloud/discussions/106

<div type='discussions-op-text'>

<sup>Originally posted by **danroth77** July 29, 2023</sup>
I've been able to integrate this code into Synology NAS, VM Manager Version of Home Assistant using HACS. The device shows up as do all the sensors, but there is no incoming data. Any tips are appreciated.</div>

**Comment by HHoppenstock** [comment]
Same here with a Delta Pro. 
It seems the integration is broken for Delta Pro. 
It works fine for my Powerstream which is connected to the same account. 
I tried to remove and reconnect the delta pro to the integration, but it didn't worked. 

After the reconnect I got 3 error log entries:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: root
Source: custom_components/ecoflow_cloud/select.py:35
Integration: EcoFlow-Cloud (documentation, issues)
First occurred: 27. Juli 2023 um 10:41:55 (461 occurrences)
Last logged: 09:46:45

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/config/custom_components/ecoflow_cloud/mqtt/ecoflow_mqtt.py", line 248, in on_json_message
    self.data.update_data(raw)
  File "/config/custom_components/ecoflow_cloud/mqtt/ecoflow_mqtt.py", line 153, in update_data
    self.__broadcast()
  File "/config/custom_components/ecoflow_cloud/mqtt/ecoflow_mqtt.py", line 157, in __broadcast
    self.__params_observable.on_next(self.params)
  File "/usr/local/lib/python3.11/site-packages/reactivex/subject/subject.py", line 59, in on_next
    super().on_next(value)
  File "/usr/local/lib/python3.11/site-packages/reactivex/observer/observer.py", line 39, in on_next
    self._on_next_core(value)
  File "/usr/local/lib/python3.11/site-packages/reactivex/subject/subject.py", line 66, in _on_next_core
    observer.on_next(value)
  File "/usr/local/lib/python3.11/site-packages/reactivex/observer/autodetachobserver.py", line 28, in on_next
    self._on_next(value)
  File "/config/custom_components/ecoflow_cloud/entities/__init__.py", line 65, in _updated
    if self._update_value(data[self._mqtt_key]):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecoflow_cloud/select.py", line 35, in _update_value
    self._attr_current_option = lval[0]
                                ~~~~^^^
IndexError: list index out of range

--------------------------------------------
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.ecoflow_cloud.mqtt.ecoflow_mqtt
Source: custom_components/ecoflow_cloud/mqtt/ecoflow_mqtt.py:300
Integration: EcoFlow-Cloud (documentation, issues)
First occurred: 27. Juli 2023 um 11:08:38 (55 occurrences)
Last logged: 09:53:56

Error parsing message

-----------------------------------------
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.ecoflow_cloud.mqtt.ecoflow_mqtt
Source: custom_components/ecoflow_cloud/mqtt/ecoflow_mqtt.py:258
Integration: EcoFlow-Cloud (documentation, issues)
First occurred: 27. Juli 2023 um 10:41:46 (71635 occurrences)
Last logged: 10:02:14

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfa in position 5: invalid start byte. Ignoring message and waiting for the next one.
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb4 in position 5: invalid start byte. Ignoring message and waiting for the next one.
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb8 in position 5: invalid start byte. Ignoring message and waiting for the next one.
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdc in position 5: invalid continuation byte. Ignoring message and waiting for the next one.
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 5: invalid start byte. Ignoring message and waiting for the next one.
