### ISSUE TITLE
Failed to set up

### ISSUE THREAD

**Issue by lowrisk75** [tolwi/hassio-ecoflow-cloud#178]
I tried with the River Pro, Delta 2 and the Powerstream, I can't get any of them to work.
I put the devices and home assistant on the same subnet, but I assume this is not the issue, nor is the firewall rule in proxmox since this using the Cloud API?

![Screenshot 2023-12-22 at 16 40 36](https://github.com/tolwi/hassio-ecoflow-cloud/assets/37781161/cf35f996-a08b-444f-bc03-be4629d3b68c)

`Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 16:36:23 (2 occurrences)
Last logged: 16:40:22

Error setting up entry Server for ecoflow_cloud
Error setting up entry Powerstream for ecoflow_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecoflow_cloud/__init__.py", line 82, in async_setup_entry
    client = EcoflowMQTTClient(hass, entry, auth)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecoflow_cloud/mqtt/ecoflow_mqtt.py", line 203, in __init__
    self.client.connect(self.auth.mqtt_url, self.auth.mqtt_port, 30)
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
TimeoutError: timed out
`

**Comment by lowrisk75** [comment]
[Uploading home-assistant_ecoflow_cloud_2023-12-22T16-44-59.093Z.log…]()

**Comment by tolwi** [comment]
`TimeoutError: timed out` - looks like integration cannot connect to mqtt broker

**Comment by zagub59** [comment]
Hey there,
Sorry to reopen this case but I get the same error trying to add my Powerstream to the integration. How did you manage to solve this ?
Thanks !

**Comment by zagub59** [comment]
Hey there,
Just in case anyone would have this issue, I had to open port TCP 8883 to IP 18.159.239.78 to make it work.
Sincerely,
