### ISSUE TITLE
MQTT initialization sometimes fails

### ISSUE THREAD

**Issue by knyghtryda** [tolwi/hassio-ecoflow-cloud#200]
I'm running into a random issue when restarting HA.  Sometimes, one of the ecoflow devices will return this error and not initialize correctly.  If I reinitialize it then it works just fine.  This looks like 

```
2024-01-18 17:50:58.988 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Mr. Fusion Pro for ecoflow_cloud
Traceback (most recent call last):
  File "/config/custom_components/ecoflow_cloud/mqtt/ecoflow_mqtt.py", line 55, in authorize
    self.token = response["data"]["token"]
                 ~~~~~~~~^^^^^^^^
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecoflow_cloud/__init__.py", line 83, in async_setup_entry
    await hass.async_add_executor_job(auth.authorize)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecoflow_cloud/mqtt/ecoflow_mqtt.py", line 59, in authorize
    raise EcoflowException(f"Failed to extract key {key} from response: {response}")
custom_components.ecoflow_cloud.mqtt.ecoflow_mqtt.EcoflowException: (("Failed to extract key 'data' from response: {'code': '0', 'message': 'Success', 'eagleEyeTraceId': 'ea1a2a623417056290554974551d0007', 'tid': ''}",), {})
```

**Comment by foxthefox** [comment]
looks to me that a direct access to data should be checked for existance before

**Comment by NameIstSchonVergeben** [comment]
I have the same Problem seen some Times

**Comment by artem-zinnatullin** [comment]
Same, after HA restart integration often goes into error state and cannot recover unless I reload it manually which is a huge bummer 😬

**Comment by MichaelRPowell** [comment]
> Same, after HA restart integration often goes into error state and cannot recover unless I reload it manually which is a huge bummer 😬

I seem to be experiencing this as well.

**Comment by knyghtryda** [comment]
@tolwi This seems to be an issue with `eagleEyeTraceId`.  Maybe Ecoflow is just throwing an extra message that isn't being expected?
