### ISSUE TITLE
Not able to connect (River 2 Pro / Home Assistant 2022.8.0 on Docker)

### ISSUE THREAD

**Issue by Softwaremaker** [tolwi/hassio-ecoflow-cloud#207]
Hi community,
Need some assistance here. First time setting this up but it failed to setup at Add Integration.

I have:
- Home Assistant 2022.8.0 on Docker
- River 2 Pro
- Unknown error occurred.

This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/ecoflow_cloud/devices/__init__.py:2
Integration: EcoFlow-Cloud (documentation, issues)
First occurred: February 5, 2024 at 10:16:43 (23 occurrences)
Last logged: 06:33:32

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 277, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 359, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/ecoflow_cloud/config_flow.py", line 24, in async_step_user
    from .devices.registry import devices
  File "/config/custom_components/ecoflow_cloud/devices/__init__.py", line 2, in <module>
    from enum import StrEnum
ImportError: cannot import name 'StrEnum' from 'enum' (/usr/local/lib/python3.10/enum.py)

**Comment by Softwaremaker** [comment]
Is this build still actively maintained ?
