### ISSUE TITLE
not working after Release  Update with HA 2024.5.0b0

### ISSUE THREAD

**Issue by andreasbuff** [tolwi/hassio-ecoflow-cloud#232]
Hello, unfortunatly Ecoflow-Integration stopped working after Upgrade to HA 2024.5.0b0 installation. 

The integration does not show any values (all values are 0).... 

Protocol:: -> 
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.ecoflow_cloud.mqtt.ecoflow_mqtt
Quelle: custom_components/ecoflow_cloud/mqtt/ecoflow_mqtt.py:309
Integration: EcoFlow-Cloud (Dokumentation, Probleme)
Erstmals aufgetreten: 19:15:28 (15 Vorkommnisse)
Zuletzt protokolliert: 19:19:09

Detected that custom integration 'ecoflow_cloud' calls async_write_ha_state from a thread at custom_components/ecoflow_cloud/entities/__init__.py, line 85: self.async_write_ha_state(). Please report it to the author of the 'ecoflow_cloud' custom integration.

Thank you for you help!

**Comment by davidbb** [comment]
Maybe just as another data point and without the AI stuff above, here's the error I see with Home Assistant 2024.5.0b4 and v0.13.2 of this integration:

```
Logger: root
Source: helpers/frame.py:203
First occurred: 9:54:34 AM (1 occurrences)
Last logged: 9:54:34 AM

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/config/custom_components/ecoflow_cloud/mqtt/ecoflow_mqtt.py", line 257, in on_json_message
    self.data.update_data(raw)
  File "/config/custom_components/ecoflow_cloud/mqtt/ecoflow_mqtt.py", line 153, in update_data
    self.__broadcast()
  File "/config/custom_components/ecoflow_cloud/mqtt/ecoflow_mqtt.py", line 157, in __broadcast
    self.__params_observable.on_next(self.params)
  File "/usr/local/lib/python3.12/site-packages/reactivex/subject/subject.py", line 59, in on_next
    super().on_next(value)
  File "/usr/local/lib/python3.12/site-packages/reactivex/observer/observer.py", line 39, in on_next
    self._on_next_core(value)
  File "/usr/local/lib/python3.12/site-packages/reactivex/subject/subject.py", line 66, in _on_next_core
    observer.on_next(value)
  File "/usr/local/lib/python3.12/site-packages/reactivex/observer/autodetachobserver.py", line 28, in on_next
    self._on_next(value)
  File "/config/custom_components/ecoflow_cloud/entities/__init__.py", line 85, in _updated
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1008, in async_write_ha_state
    self.hass.verify_event_loop_thread("async_write_ha_state")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'ecoflow_cloud' calls async_write_ha_state from a thread at custom_components/ecoflow_cloud/entities/__init__.py, line 85: self.async_write_ha_state(). Please report it to the author of the 'ecoflow_cloud' custom integration. 
```

**Comment by tommyl2210** [comment]
same issue with the final release of 2024.5.0
Thanks for looking into it!

**Comment by Milli42** [comment]
Same issue 2024.5.0

**Comment by polarbaerchen2000** [comment]
I habe the same problem. Integration not working after update.

Milli42 ***@***.***> schrieb am Do., 2. Mai 2024, 04:19:

**Comment by fingerhandschuh** [comment]
Same issue after updating to the final release of 2024.5.0 with v0.13.2 of this integration.
Thanks for looking into it!

**Comment by Cricri6799** [comment]
Samedi issue nothing work

**Comment by Stratovarius666** [comment]
Same issue. No news?

**Comment by TrilIiard** [comment]
Same here after updating to 2023.05 stable. Using a backup to undo the Update and everything is up and running fine again. Just skip the 2024.05 Update until Ecoflow cloud gets an update

**Comment by andreasbuff** [comment]
> Same here after updating to 2023.05 stable. Using a backup to undo the Update and everything is up and running fine again. Just skip the 2024.05 Update until Ecoflow cloud gets an update

I have setup an new HA-VM on a Proxmox Cluster with 2024.4. and only Ecoflow-Integartion on it. With Remot-Home-Assistant, you can link the two HAs to get sensors from the "working EcoFlow-Integration" into your normal HA (https://github.com/custom-components/remote_homeassistant; not very nice but it is working).

**Comment by maddinhome** [comment]
Someone here had a similar problem since HA 2024.5.xb, maybe this will help to find a solution:

https://community.home-assistant.io/t/how-to-fix-custom-integration-brematic-calls-async-write-ha-state/722238

**Comment by Kristian-R** [comment]
> Someone here had a similar problem since HA 2024.5.xb, maybe this will help to find a solution:
> 
> https://community.home-assistant.io/t/how-to-fix-custom-integration-brematic-calls-async-write-ha-state/722238
> 
> https://community.home-assistant.io/t/how-to-fix-custom-integration-brematic-calls-async-write-ha-state/722238/2

This seems to be the solution. I modified my ecoflow-integration wit the Addon „File Editor“: replaced the instances of 
`self.async_write_ha_state()` 
With
`self.schedule_update_ha_state()`

in `custom_components/ecoflow_cloud/entitities/__init__.py`
and
`custom_components/ecoflow_cloud/sensor.py`

Appears to be working again for me. Hope I did not miss a place.

**Comment by andreasbuff** [comment]
> > Someone here had a similar problem since HA 2024.5.xb, maybe this will help to find a solution:
> > https://community.home-assistant.io/t/how-to-fix-custom-integration-brematic-calls-async-write-ha-state/722238
> > https://community.home-assistant.io/t/how-to-fix-custom-integration-brematic-calls-async-write-ha-state/722238/2
> 
> This seems to be the solution. I modified my ecoflow-integration wit the Addon „File Editor“: replaced the instances of `self.async_write_ha_state()` With `self.schedule_update_ha_state()`
> 
> in `custom_components/ecoflow_cloud/entitities/__init__.py` and `custom_components/ecoflow_cloud/sensor.py`
> 
> Appears to be working again for me. Hope I did not miss a place.

Yes!  Thanks @Kristian-R !! This does the trick. Be aware, that there are 2 "__init__.py".   you have to change the one in "custom_components/ecoflow_cloud/entitities/__init__.py" :-)   It is working for me too.

**Comment by saschamb1** [comment]
Great Job @Kristian-R . It works. :-)

**Comment by maddinhome** [comment]
Then I'm glad I found the post and we can solve the problem.

@Kristian-R Thanks for checking which py files needed to be changed.

it also works for me...

**Comment by Kristian-R** [comment]
> Great Job @Kristian-R . It works. :-)

Thanks go out to @maddinhome for pointing at the other thread.

**Comment by Fyr42** [comment]
Thx for the patch

**Comment by takecare0** [comment]
Thank you very much

**Comment by Stratovarius666** [comment]
Sorry for the stupid question.
Now that the patch has been issued, what should be done? Do I need to re-download and apply the Ecoflow-Cloud integration?
Or do I have to physically modify the two files "init.py" and "sensor.py"?

Thanks

**Comment by Nid01** [comment]
> Sorry for the stupid question. Now that the patch has been issued, what should be done? Do I need to re-download and apply the Ecoflow-Cloud integration? Or do I have to physically modify the two files "init.py" and "sensor.py"?
> 
> Thanks

@Stratovarius666 Until @tolwi releases a new version of the integration with the solution you need to modify the two files.

**Comment by Stratovarius666** [comment]
Thank you so much!

Il giorno gio 2 mag 2024 alle ore 18:40 Nid01 ***@***.***> ha
scritto:

**Comment by Chimpepe** [comment]
Great job guys!

**Comment by severine24700** [comment]
Fantastic, it works like a charm again. Thank you for all your hard work!

**Comment by TELY01** [comment]
Great job bro @Kristian-R

**Comment by DauntlessEagle** [comment]
Thank you for this. Data is now working but switches selectors and sliders for example ac enable disable, discharge limits can no longer be set on Delta Pro.

**Comment by YoppY14** [comment]
Thank you for the fix! It works.
At least in part: there are still issues following the update.
The refresh rates are no longer respected (for example, it can take 20 minutes without any feedback on the battery level) and some switches no longer work.
For example, the DC switch "dc_12v_enabled" of a river 2
returns this message:
`Failed to call the switch/turn_on service. Detected that custom integration 'ecoflow_cloud' calls async_write_ha_state from a thread at custom_components/ecoflow_cloud/sensor.py, line 340: self.schedule_update_ha_state(). Please report it to the author of the 'ecoflow_cloud' custom integration.`

**Comment by Kristian-R** [comment]
>…
 custom_components/ecoflow_cloud/sensor.py, line 340: self.schedule_update_ha_state(). Please report it to the author of the 'ecoflow_cloud' custom integration.`
> 
> Edit : in logs, other line : `Detected that custom integration 'ecoflow_cloud' calls async_write_ha_state from a thread at custom_components/ecoflow_cloud/sensor.py, line 352: self.schedule_update_ha_state(). Please report it to the author of the 'ecoflow_cloud' custom integration.`

Did you replace all instances of `self.schedule_update_ha_state()`?

Try again after restarting Homeassistant - just reloading the integration was not sufficient for me.

Kind regards
KristianR

**Comment by YoppY14** [comment]
Okay, I think I've found the solution. I edited the files with the "File Editor" and even though I modified and saved the sensor.py file, the file was not actually modified. Likely a permissions issue. 
I ended up uninstalling/reinstalling, deleting the files to completely recreate them with the modifications. And everything was back in order after the restart.
Thanks again!

**Comment by dennisbech** [comment]
> > Someone here had a similar problem since HA 2024.5.xb, maybe this will help to find a solution:
> > https://community.home-assistant.io/t/how-to-fix-custom-integration-brematic-calls-async-write-ha-state/722238
> > https://community.home-assistant.io/t/how-to-fix-custom-integration-brematic-calls-async-write-ha-state/722238/2
> 
> This seems to be the solution. I modified my ecoflow-integration wit the Addon „File Editor“: replaced the instances of `self.async_write_ha_state()` With `self.schedule_update_ha_state()`
> 
> in `custom_components/ecoflow_cloud/entitities/__init__.py` and `custom_components/ecoflow_cloud/sensor.py`
> 
> Appears to be working again for me. Hope I did not miss a place.

Hey Kristian it works with powersteam, but not my delta 2 do you have ideer hear?

**Comment by Kristian-R** [comment]
> > > Someone here had a similar problem since HA 2024.5.xb, maybe this will help to find a solution:
> > > https://community.home-assistant.io/t/how-to-fix-custom-integration-brematic-calls-async-write-ha-state/722238
> > > https://community.home-assistant.io/t/how-to-fix-custom-integration-brematic-calls-async-write-ha-state/722238/2
> > 
> > 
> > This seems to be the solution. I modified my ecoflow-integration wit the Addon „File Editor“: replaced the instances of `self.async_write_ha_state()` With `self.schedule_update_ha_state()`
> > in `custom_components/ecoflow_cloud/entitities/__init__.py` and `custom_components/ecoflow_cloud/sensor.py`
> > Appears to be working again for me. Hope I did not miss a place.
> 
> Hey Kristian it works with powersteam, but not my delta 2 do you have ideer hear?

Hi Dennis,

for my River 2 Max it is working. Sorry I don't have an idea whats going wrong for the Delta 2.

Make sure to replace all occurences (One occurence in init.py / five occurences in sensors.py) / Restart Homeassistant to be sure that the changes take effect.

Kind regards
Kristian

**Comment by dennisbech** [comment]
year, no it works, I miss 4 occurences sorry thanks for help:_)

**Comment by ekusinski** [comment]
Hi
It's ok for powerstream but not with delta pro + smart extra battery

**Comment by MikeTango** [comment]
With the maintainer's location set as Kyiv, Ukraine, and zero activity for the last two months i suggest someone knowledgeable fork this and patch it so users can run a working integration out of the box. Hope the guy is all right.

**Comment by danbrown1010** [comment]
Saved me too! Nice work - thx!

**Comment by ppiwowar** [comment]
Worked for DELTA MAX for m e as well! Thanks!

**Comment by KarinBerg** [comment]
This issue will be fix with this pull request https://github.com/tolwi/hassio-ecoflow-cloud/pull/234 once it is merge and released by the repository owner @tolwi 

In the meantime, you can modify the files from the pull request locally on your Home Assistant installation. 

Thanks to @Kristian-R and @maddinhome

**Comment by MaGroGS** [comment]
Thanks to All of You for great job! Delta Max works fine again!
By the way: in the logs of HA on RPI3 I found the following issue message. Please have a look at it.
Greetings, MaGroGS
---
Logger: homeassistant.const
Quelle: helpers/deprecation.py:206
Erstmals aufgetreten: 22:24:03 (1 Vorkommnisse)
Zuletzt protokolliert: 22:24:03

POWER_WATT was used from ecoflow_cloud, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPower.WATT instead, please report it to the author of the 'ecoflow_cloud' custom integration

**Comment by james-troup** [comment]
Spotted this fix couple weeks ago, but taken me a while to actually try it... Just a quick comment to say tested now tested and back up and running. Thank you

**Comment by dannytsang** [comment]
Tested this as well. Works with my Delta 2.
