### ISSUE TITLE
1.1.0-pre2 strange errors in logs [River 2 Max]

### ISSUE THREAD

**Issue by chertvl** [tolwi/hassio-ecoflow-cloud#297]
Updated to 1.1.0-pre2 and get some strange errors in core logs.
Looks like all works as well, but error during HA start tolds about something wrong:
```
 ERROR (MainThread) [homeassistant.components.select]  ---  5 times

Error adding entity select.ecoflow_dc_12v_charge_current for domain select with platform ecoflow_cloud
Error adding entity select.ecoflow_dc_mode for domain select with platform ecoflow_cloud
Error adding entity select.ecoflow_screen_timeout for domain select with platform ecoflow_cloud
Error adding entity select.ecoflow_unit_timeout for domain select with platform ecoflow_cloud
Error adding entity select.ecoflow_ac_timeout for domain select with platform ecoflow_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 598, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 912, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1366, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1011, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 145, in state
    current_option = self.current_option
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 165, in current_option
    return self._attr_current_option
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DictSelectEntity' object has no attribute '__attr_current_option'. Did you mean: '_attr_current_option'?
```

**Comment by SBozhyi** [comment]
1.1.0-pre3 - same error (Delta 2)
