### ISSUE TITLE
Question/Enhancement/Concept: mqtt client ids (public API)

### ISSUE THREAD

**Issue by giovanne123** [tolwi/hassio-ecoflow-cloud#306]
**Question and mybe enhancement regarding mqtt client connects and subscribing to topics for devices.
public API**

@tolwi 

**Question: can the integration using the public API be enhanced to only have one client_id and let new devices only subscribe to needed topics?**

**Why:**
As we now from Facebook there must be caution with limited client_ids per day for the EF developer/public API:
https://github.com/tolwi/hassio-ecoflow-cloud/blob/2656283f345d3142c1a644de95567046e6d893d5/custom_components/ecoflow_cloud/api/public_api.py#L19

If I'm right, there is created a mqtt client id for every device with is added by the integration and enhanced with current day of month.
![image](https://github.com/user-attachments/assets/0fc18cea-7434-4c3c-9d91-cc3bb697a499)

If you have much devices this can be tricky reaching the limitations.
Also in some special situation (updates, restarts, ...)

I am not sure if this is needed inside the integration, but for my beside python trials, I only connected once with one client_id and by subscribing to the topics which I'm interested in and react on_message (some snipplets from my python trials).
```
...
        client_id = "ecoflow_api_mqtt_XYZ"
...
        client = mqtt.Client(client_id, clean_session=True, userdata=None, protocol=mqtt.MQTTv311, transport="tcp")
...
        connected_flag = True  # Set flag
        LOGGER.info("Connected to MQTT Broker!")
        client.subscribe(topicPLUG3, qos=1)
        time.sleep(0.5)
        client.subscribe(topicPLUG2, qos=1)
        time.sleep(0.5)
        client.subscribe(topicPLUG1, qos=1)
        time.sleep(0.5)
        client.subscribe(topicPS1, qos=1)
        time.sleep(0.5)
        client.subscribe(topicPS2, qos=1)
...
on_message(client, userdata, msg):
    try:
        # Decode the message payload as a string
        #print("Topic: " + msg.topic)
        decoded_message = msg.payload.decode("utf-8")
        #pprint(decoded_message)
        # Parse the JSON data
        message_data = json.loads(decoded_message)
        #pprint(message_data)

        #Plug 1, 2 or 3
        if msg.topic == topicPLUG1:

        #Powerstream 1 or 2
        if msg.topic == topicPS1:

...
```

**Some background why I came to this:**
I came to this because I today ran into trouble when updating my PiOS which includes docker itself to be updated (i am using HA in docker container), which lead in container restarts and therefore integration/devices restart.
So after this I encountered in HA that the mqtt connection failed with error code "5":
![image](https://github.com/user-attachments/assets/aeec5136-f9a7-4dd3-b7e9-e3649f0d6b65)

In my previous activities, using python scripts and also today for the integration I learned that this error is related to too much clients(ids) connected to the EF mqtt broker and the connection is blocked.
**Only solution is to create new AccessKey/SecretKey pairs** (and for own scripts new certificateAccount/certificatePassword too, this does the integration inside itself)  
**So after all this Key/Secret stuff created new - everything was working again fine.**

**Comment by tolwi** [comment]
starting from 1.1.0-pre1 integration uses 1 mqtt connection for all devices in group.
hope it will be released next week.

**Comment by tolwi** [comment]
btw during testing i encountered issues even with one client_id, that is why there is some "rotation" - https://github.com/tolwi/hassio-ecoflow-cloud/blob/main/custom_components/ecoflow_cloud/api/public_api.py#L40

**Comment by giovanne123** [comment]
> starting from 1.1.0-pre1 integration uses 1 mqtt connection for all devices in group. hope it will be released next week.

@tolwi 
which release do you mean for next week including the 1 mqtt connection (typo above?)? 
Because you are already on v1.1.0-pre7 and I currently have installed v1.1.0-pre6.

**Comment by giovanne123** [comment]
@tolwi ,
ome question, when updating to 1.1.0 from pre6/7 is it necessary to recreate the devices to take the ONE client_id  affect?

**Comment by giovanne123** [comment]
@tolwi,
can you please describe a bit how the creation of client_id, mqtt connection is working in current version v1.2.0?

I encountered still a problem sometimes when e.g. updating HA and restarting therefore. Maybe because I have 4 devices in Ecoflow Cloud and a separate python script (using one client_id) running and reaching the client_id limit ...
Recreate Key/Secret everytime solves the problem!
Maybe this is also the reason why often the people are raising issues...
Are you using only one mqtt connection per account(key/value)?
```
custom_components.ecoflow_cloud.api.EcoflowException: (('signature is wrong',), {})
2024-09-26 14:13:53.713 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/ecoflow_cloud/api/public_api.py", line 80, in quota_all
    raw = await self.call_api("/device/quota/all", {"sn": sn})
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecoflow_cloud/api/public_api.py", line 100, in call_api
    return await self._get_json_response(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecoflow_cloud/api/__init__.py", line 80, in _get_json_response
    raise EcoflowException(f"{response_message}")
custom_components.ecoflow_cloud.api.EcoflowException: (('signature is wrong',), {})
2024-09-26 14:13:55.030 ERROR (Thread-7 (_thread_main)) [custom_components.ecoflow_cloud.api.ecoflow_mqtt] MQTT connect: The connection was refused. (Hassio-open-exxxxxxxxxxxxxxxxxxxxxxxeec5-Powerstream-2-20240926) - None
2024-09-26 14:13:55.031 ERROR (Thread-7 (_thread_main)) [custom_components.ecoflow_cloud.api.ecoflow_mqtt] Unexpected MQTT Socket disconnection : <ssl.SSLSocket fd=76, family=2, type=1, proto=6, laddr=('192.xxx.0.111', 55459), raddr=('18.xxx.239.78', 8883)>
2024-09-26 14:13:55.044 ERROR (Thread-6 (_thread_main)) [custom_components.ecoflow_cloud.api.ecoflow_mqtt] MQTT connect: The connection was refused. (Hassio-open-exxxxxxxxxxxxxxxxxxxxxxxeec5-Delta-2-20240926) - None
2024-09-26 14:13:55.045 ERROR (Thread-6 (_thread_main)) [custom_components.ecoflow_cloud.api.ecoflow_mqtt] Unexpected MQTT Socket disconnection : <ssl.SSLSocket fd=79, family=2, type=1, proto=6, laddr=('192.xxx.0.111', 48077), raddr=('18.xxx.239.78', 8883)>
2024-09-26 14:15:55.144 ERROR (Thread-7 (_thread_main)) [custom_components.ecoflow_cloud.api.ecoflow_mqtt] MQTT connect: The connection was refused. (Hassio-open-exxxxxxxxxxxxxxxxxxxxxxxeec5-Powerstream-2-20240926) - None
2024-09-26 14:15:55.145 ERROR (Thread-7 (_thread_main)) [custom_components.ecoflow_cloud.api.ecoflow_mqtt] Unexpected MQTT Socket disconnection : <ssl.SSLSocket fd=78, family=2, type=1, proto=6, laddr=('192.xxx.0.111', 42147), raddr=('18.xxx.239.78', 8883)>

```
 
Why are you using the "group" in the client_id? Because the "name" (open-xxxx) makes it already unique? Makes it sense to remove it from client_id?
What is the intention of the group entry/option at all?
Also the "datetime" part maybe can be removed to have more security to not reach the client_id limits? (for my python script e.g. I am only using one fix client_id for all devices per key/secret (certificateAccount/-Password) over all the time)

![image](https://github.com/user-attachments/assets/d377b41a-9f8b-4c09-904e-25a03dc2cb0b)

So far I have used the integration, group this way (because I insert my key/secret) and do not need the group:
my group name is identical to device name: (maybe I do not use your intention the right way?)
![image](https://github.com/user-attachments/assets/6c7d30a3-8d6e-44bb-8434-807a79bdae63)

Would be fine if you answer to get a bit insights.
Final question, is your planned one connection (https://github.com/tolwi/hassio-ecoflow-cloud/issues/306#issuecomment-2321209246) already in v1.2.0?

@tolwi , **and many many thanks to you for this integration!** Beside this client_id topic it is working alsolutely stable for me :-)
