### ISSUE TITLE
Powerstream, Open API (with latest codebase), some problems / bugs

### ISSUE THREAD

**Issue by Dev-Fabry** [tolwi/hassio-ecoflow-cloud#315]
Hello, I have the following problems:

* Sometimes after days of regular operation the integration NO longer receives data from the Cloud.
It has already happened to me twice and by restarting HA it works again
There may have been a nightly restart of HA between the last working session and the first session in the morning where no data was received (until a new restart). Not sure about this but possible.

* Sometimes restarting HA with the integration that was working then the log gets filled with MQTT Login failed messages (MQTT connect: The connection was refused).
However, the integration is working, it's as if upon restart it had not closed the previous connection, in an attempt to make a new one it does NOT succeed but it still works using the old one (and filling the logs with continuous attempts to make a new one)

* The log reports this warning for a few days, after a HA restart

> Detected blocking call to import_module with args ('google._upb._message',) inside the event loop by custom integration 'ecoflow_cloud' at custom_components/ecoflow_cloud/devices/internal/proto/ecopacket_pb2.py, line 5: from google.protobuf import descriptor as _descriptor (offender: /usr/local/lib/python3.12/site-packages/google/protobuf/internal/api_implementation.py, line 41: mod = importlib.import_module(mod_name)), please create a bug report at https://github.com/tolwi/hassio-ecoflow-cloud/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 752, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/ecoflow_cloud/__init__.py", line 214, in async_setup_entry
    device = api_client.configure_device(device_data.sn, device_data.name, device_data.device_type,
  File "/config/custom_components/ecoflow_cloud/api/public_api.py", line 58, in configure_device
    from custom_components.ecoflow_cloud.devices.registry import device_by_product
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/ecoflow_cloud/devices/registry.py", line 3, in <module>
    from .internal import (delta2 as internal_delta2,
  File "<frozen importlib._bootstrap>", line 1415, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/ecoflow_cloud/devices/internal/powerstream.py", line 15, in <module>
    from .proto import ecopacket_pb2 as ecopacket, powerstream_pb2 as powerstream
  File "<frozen importlib._bootstrap>", line 1415, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/ecoflow_cloud/devices/internal/proto/ecopacket_pb2.py", line 5, in <module>
    from google.protobuf import descriptor as _descriptor

**Comment by Dev-Fabry** [comment]
> Hello, I have the following problems:
> 
>     * Sometimes after days of regular operation the integration NO longer receives data from the Cloud.
>       It has already happened to me twice and by restarting HA it works again
>       There may have been a nightly restart of HA between the last working session and the first session in the morning where no data was received (until a new restart). Not sure about this but possible.
> 
>     * Sometimes restarting HA with the integration that was working then the log gets filled with MQTT Login failed messages (MQTT connect: The connection was refused).
>       However, the integration is working, it's as if upon restart it had not closed the previous connection, in an attempt to make a new one it does NOT succeed but it still works using the old one (and filling the logs with continuous attempts to make a new one)

Hi,
I have to correct this, it's not true that the integration works with the old connection.
When HA restarts it reads the data (making you believe that everything is working) but then it no longer updates them and only that first reading remains, plus the Log which is filled with MQTT errors

Maybe this is what also caused the problem in the first point.
The integration was working, then a HA reboot blocked access to the data. 

Now I'll try to take the supplement for 30 minutes or more to see if it recovers
Maybe I'll also test with the Application API because I have to try something on the old interface.

**Comment by giovanne123** [comment]
Maybe -> https://github.com/tolwi/hassio-ecoflow-cloud/issues/306

**Comment by Dev-Fabry** [comment]
> Maybe -> #306 (If so, only new Key/Secret will solve the issue)

Yes, first two problems seems to be your #306 

But I don't think there is a daily reset of orphaned clients_id.

I removed the integration for about 18 hours and today recreating it immediately gave the problem.
Midnight has passed in China too.

**Comment by giovanne123** [comment]
I don't write that there is a daily client_id reset 
-> in my post I summarized at the end that only helps: only new Key/Secret will solve the issue

**Comment by giovanne123** [comment]
OK, solutiion for users without support possibilities from Ecoflow is the recreation of Key/secret.

Questions to known Ecoflow contacts support emails (default and developer), facebook group never ended in an answer or positiv feedback

**Comment by giovanne123** [comment]
And it is only blocked for mqtt (certicateAccout/-password) the key/Secret can still be used for http request but the certicateAccout is linked to key Secret and there only it is possible to create one 🫤

**Comment by Dev-Fabry** [comment]
So the correct solution could be for the integration during the configuration phase to ask if we already have an id (and everything else needed) to reuse and if so, ask us to provide it with the data

Otherwise it creates a new one, but stores it somewhere to be used between reboots and also allows an export of this data for any reinstallations that delete the saved data

**Comment by giovanne123** [comment]
And in addition only one client_id per added integration (same key/secret) ... currently there is created a client_id per added device in the integration.

**Comment by Dev-Fabry** [comment]
@tolwi 
I have installed 1.1.0 with fresh install and a new pair (the old one compromised by too ids) of keys 

>     * Sometimes restarting HA with the integration that was working then the log gets filled with MQTT Login failed messages (MQTT connect: The connection was refused).
>       However, the integration is working, it's as if upon restart it had not closed the previous connection, in an attempt to make a new one it does NOT succeed but it still works using the old one (and filling the logs with continuous attempts to make a new one)
> 
I believe these errors could have been corrected by
https://github.com/tolwi/hassio-ecoflow-cloud/commit/9df7fd636c9bb02b343cc55ba31c9a1e053052da
Obviously there is no counter-proof but for now we are confident

I still had 4 MQTT errors on first use, but after a further restart of HA no other errors have reappeared in the registry yet

>     * The log reports this warning for a few days, after a HA restart
> 
> 
> > Detected blocking call to import_module with args ('google._upb._message',) inside the event loop by custom integration 'ecoflow_cloud' at custom_components/ecoflow_cloud/devices/internal/proto/ecopacket_pb2.py, line 5: from google.protobuf import descriptor as _descriptor (offender: /usr/local/lib/python3.12/site-packages/

I don't know if this error has been fixed by https://github.com/tolwi/hassio-ecoflow-cloud/commit/8d161dad24db65b0311274765c512e59541de5fa
But in any case for now it no longer appears in the register
