### ISSUE TITLE
MQTT Error since update to 1.1.0

### ISSUE THREAD

**Issue by bobj2104** [tolwi/hassio-ecoflow-cloud#332]
Hello,
Yesterday I updated the EcoFlow addon in homeassistant to 1.1.0. before the update I used 1.1.0pre7 and it was working fine. 
Now all values of my EcoFlow devices don’t update anymore. They seem to get one new value after a reboot, but not more. I tried deleting and reconfiguring the addon but it behaves the same. 

In the log it says:

2024-09-10 20:14:39.465 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/ecoflow_cloud/api/public_api.py", line 80, in quota_all
    raw = await self.call_api("/device/quota/all", {"sn": sn})
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecoflow_cloud/api/public_api.py", line 100, in call_api
    return await self._get_json_response(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecoflow_cloud/api/__init__.py", line 80, in _get_json_response
    raise EcoflowException(f"{response_message}")
custom_components.ecoflow_cloud.api.EcoflowException: (('signature is wrong',), {})

2024-09-10 20:16:59.944 ERROR (Thread-10 (_thread_main)) [custom_components.ecoflow_cloud.api.ecoflow_mqtt] MQTT connect: The connection was refused. (Hassio-open-3f8a1e5b2f3642e2887f9966aecf3f66-Home-20240910) - None
2024-09-10 20:16:59.945 ERROR (Thread-10 (_thread_main)) [custom_components.ecoflow_cloud.api.ecoflow_mqtt] Unexpected MQTT Socket disconnection : <ssl.SSLSocket fd=14, family=2, type=1, proto=6, laddr=('192.168.68.133', 47913), raddr=('18.159.239.78', 8883)>

**Comment by bobj2104** [comment]
After retrieving a new access and secret key from Ecoflow everything works fine again.
