### ISSUE TITLE
Values not updating and responding after initial loading of integration

### ISSUE THREAD

**Issue by DrDimoner** [tolwi/hassio-ecoflow-cloud#345]
My Powerstream (API) and Delta Max (API) are not updating their entities and I can't input anything either. When I reload the integration, the entities are getting updated to the current value once, but after that it's not updating anymore. Everything works fine in the Ecoflow App. There are 4 Errors in the logs:

This error originated from a custom integration.

Logger: custom_components.ecoflow_cloud.api.ecoflow_mqtt
Source: custom_components/ecoflow_cloud/api/ecoflow_mqtt.py:129
integration: Ecoflow-Cloud (documentation, issues)
First occurred: 09:50:06 (2 occurrences)
Last logged: 09:51:16

Bad logger message: Message publish failed: The client is not currently connected. (('Error on topic /open/open-e7cef9ecaaae4159985c99af06d68db0/HW51ZEH4SF6F6395/set and message {"from": "HomeAssistant", "id": "999980259", "version": "1.0", "sn": "HW51ZEH4SF6F6395", "cmdCode": "WN511_SET_SUPPLY_PRIORITY_PACK", "params": {"supplyPriority": 0}}',))
Bad logger message: Message publish failed: The client is not currently connected. (('Error on topic /open/open-e7cef9ecaaae4159985c99af06d68db0/DAEBZ5KE9152643/set and message {"from": "HomeAssistant", "id": "999980259", "version": "1.0", "moduleType": 1, "operateType": "dcOutCfg", "moduleSn": "DAEBZ5KE9152643", "params": {"enabled": 1}}',))

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/ecoflow_cloud/api/__init__.py:80
integration: Ecoflow-Cloud (documentation, issues)
First occurred: 09:53:18 (24 occurrences)
Last logged: 09:55:17

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/ecoflow_cloud/api/public_[api.py](https://api.py/)", line 80, in quota_all
    raw = await self.call_api("/device/quota/all", {"sn": sn})
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecoflow_cloud/api/public_[api.py](https://api.py/)", line 100, in call_api
    return await self._get_json_response(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecoflow_cloud/api/__init__.py", line 80, in _get_json_response
    raise EcoflowException(f"{response_message}")
custom_components.ecoflow_cloud.api.EcoflowException: (('signature is wrong',), {})

This error originated from a custom integration.

Logger: custom_components.ecoflow_cloud.api.ecoflow_mqtt
Source: custom_components/ecoflow_cloud/api/ecoflow_mqtt.py:112
integration: Ecoflow-Cloud (documentation, issues)
First occurred: 09:48:15 (34 occurrences)
Last logged: 09:56:16

MQTT connect: The connection was refused. (Hassio-open-e7cef9ecaaae4159985c99af06d68db0-Home-20240923) - None
MQTT connect: The connection was refused. (Hassio-open-e7cef9ecaaae4159985c99af06d68db0-Home_2-20240923) - None

This error originated from a custom integration.

Logger: custom_components.ecoflow_cloud.api.ecoflow_mqtt
Source: custom_components/ecoflow_cloud/api/ecoflow_mqtt.py:63
integration: Ecoflow-Cloud (documentation, issues)
First occurred: 09:48:15 (34 occurrences)
Last logged: 09:56:16

Unexpected MQTT Socket disconnection : <ssl.SSLSocket fd=19, family=2, type=1, proto=6, laddr=('[192.168.188.51](https://192.168.188.51/)', 42131), raddr=('[18.159.239.78](https://18.159.239.78/)', 8883)>
Unexpected MQTT Socket disconnection : <ssl.SSLSocket fd=56, family=2, type=1, proto=6, laddr=('[192.168.188.51](https://192.168.188.51/)', 34569), raddr=('[18.159.239.78](https://18.159.239.78/)', 8883)>
Unexpected MQTT Socket disconnection : <ssl.SSLSocket fd=56, family=2, type=1, proto=6, laddr=('[192.168.188.51](https://192.168.188.51/)', 40637), raddr=('[18.159.239.78](https://18.159.239.78/)', 8883)>
Unexpected MQTT Socket disconnection : <ssl.SSLSocket fd=20, family=2, type=1, proto=6, laddr=('[192.168.188.51](https://192.168.188.51/)', 42939), raddr=('[18.159.239.78](https://18.159.239.78/)', 8883)>
Unexpected MQTT Socket disconnection : <ssl.SSLSocket fd=20, family=2, type=1, proto=6, laddr=('[192.168.188.51](https://192.168.188.51/)', 51173), raddr=('[18.159.239.78](https://18.159.239.78/)', 8883)>

**Comment by DrDimoner** [comment]
The Issue has been discussed more here: https://github.com/tolwi/hassio-ecoflow-cloud/issues/341
didn't see this before, so I have closed the issue.
