### ISSUE TITLE
EcoFlow Delta 2 Max Integration issue

### ISSUE THREAD

**Issue by gilbert76** [tolwi/hassio-ecoflow-cloud#73]
I have the following problem is integration from the Delta2Max. 

The following error look, I find in my home assistant ( can you help me?) : 

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: aiohttp.server
Source: custom_components/ecoflow_cloud/sensor.py:7 
Integration: EcoFlow-Cloud (documentation, issues) 
First occurred: 18:34:41 (11 occurrences) 
Last logged: 18:35:34

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 81, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 281, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 368, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/ecoflow_cloud/config_flow.py", line 24, in async_step_user
    from .devices.registry import devices
  File "/config/custom_components/ecoflow_cloud/devices/registry.py", line 3, in <module>
    from custom_components.ecoflow_cloud.devices.delta2 import Delta2
  File "/config/custom_components/ecoflow_cloud/devices/delta2.py", line 7, in <module>
    from ..sensor import LevelSensorEntity, RemainSensorEntity, TempSensorEntity, CyclesSensorEntity, \
  File "/config/custom_components/ecoflow_cloud/sensor.py", line 7, in <module>
    from homeassistant.const import (PERCENTAGE, POWER_WATT, TEMP_CELSIUS,
ImportError: cannot import name 'UnitOfElectricPotential' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

**Comment by tolwi** [comment]
looks like you have a very outdated Home Assistant setup

**Comment by gilbert76** [comment]
You are right
